name: build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: setup go environment
        run: |
          echo "public_repo_name=$(curl https://api.github.com/users/resotto/repos | jq '.[]["full_name"] | select(. | contains("${{ github.repository }}"))')" >> $GITHUB_ENV
          echo $public_repo_name
      - name: set goprivate if this repo is private
        if: ${{ $public_repo_name == "" }}
        run: |
          go env -w GOPRIVATE=github.com/${{ github.repository }}
          go env GOPRIVATE
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run golint, go vet, and go test
        run: |
          go vet -v ./...
          cd internal/gochk
          ls
          go test -v ./...

  build_and_push_to_ghcr:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build Docker Image and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./build/Dockerfile
          tags: ghcr.io/${{ github.repository }}:latest
